services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sizeapi-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SizeApi@2025!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sizeapi-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SizeApi@2025! -Q 'SELECT 1' -C"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  sizeapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sizeapi-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - sizeapi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlserver_data:

networks:
  sizeapi-network:
    driver: bridge